# Synthetic fixture ownership is exact and documentation-safe.
ra_fixture_spec() { case "$1" in fixture_a) jq -cn '{name:"fixture_a",tun:"podlaz-accept-a0",cidr:"198.18.0.1/32",table:"51820",route:"198.51.100.254/32",rule_a:"198.51.100.254/32",rule_b:"198.51.100.253/32",priority_a:9999,priority_b:10000,nft_table:"podlaz_accept_a",dns_link:"podlaz-accept-adns0",dns_server:"192.0.2.53",dns_domain:"~accept-a.invalid"}' ;; fixture_b) jq -cn '{name:"fixture_b",tun:"podlaz-accept-b0",cidr:"198.18.62.1/32",table:"51962",route:"203.0.113.62/32",rule_a:"203.0.113.62/32",rule_b:"203.0.113.63/32",priority_a:10999,priority_b:11000,nft_table:"podlaz_accept_b",dns_link:"podlaz-accept-bdns0",dns_server:"192.0.2.54",dns_domain:"~accept-b.invalid"}' ;; *) return 1 ;; esac; }
ra_fixture_assert_free() { local spec="$1" tun dns nft pa pb table count; tun="$(jq -r '.tun' <<<"$spec")"; dns="$(jq -r '.dns_link' <<<"$spec")"; nft="$(jq -r '.nft_table' <<<"$spec")"; pa="$(jq -r '.priority_a' <<<"$spec")"; pb="$(jq -r '.priority_b' <<<"$spec")"; table="$(jq -r '.table' <<<"$spec")"; ra_capture ip -j -d link show || return 1; count="$(jq --arg a "$tun" --arg b "$dns" '[.[]?|select(.ifname==$a or .ifname==$b)]|length' <<<"$RA_CAPTURE")" || return 1; [[ "$count" == 0 ]] || return 1; ra_capture nft -j list tables || return 1; count="$(jq --arg n "$nft" '[.nftables[]?.table?|select(.family=="inet" and .name==$n)]|length' <<<"$RA_CAPTURE")" || return 1; [[ "$count" == 0 ]] || return 1; ra_capture ip -4 rule show || return 1; count="$(awk -v a="$pa" -v b="$pb" '$1==a":"||$1==b":"{n++} END{print n+0}' <<<"$RA_CAPTURE")" || return 1; [[ "$count" == 0 ]] || return 1; ra_capture ip -j -4 route show table all || return 1; count="$(jq --arg t "$table" '[.[]?|select(((.table//"")|tostring)==$t)]|length' <<<"$RA_CAPTURE")" || return 1; [[ "$count" == 0 ]]; }
ra_fixture_acquire() { local name="$1" spec identity tun cidr table route rule_a rule_b pa pb nft dns server domain; spec="$(ra_fixture_spec "$name")" || return 1; ra_fixture_assert_free "$spec" || { ra_die "ownership fixture identity is not free"; return 1; }; identity="$(jq -c '.+{current_route:.route}' <<<"$spec")" || return 1; ra_mut_begin_acquire "$name" network_fixture "$identity" || return 1; tun="$(jq -r '.tun' <<<"$spec")"; cidr="$(jq -r '.cidr' <<<"$spec")"; table="$(jq -r '.table' <<<"$spec")"; route="$(jq -r '.route' <<<"$spec")"; rule_a="$(jq -r '.rule_a' <<<"$spec")"; rule_b="$(jq -r '.rule_b' <<<"$spec")"; pa="$(jq -r '.priority_a' <<<"$spec")"; pb="$(jq -r '.priority_b' <<<"$spec")"; nft="$(jq -r '.nft_table' <<<"$spec")"; dns="$(jq -r '.dns_link' <<<"$spec")"; server="$(jq -r '.dns_server' <<<"$spec")"; domain="$(jq -r '.dns_domain' <<<"$spec")"; ra_capture ip tuntap add dev "$tun" mode tun || return 1; ra_capture ip link set dev "$tun" up || return 1; ra_capture ip -4 address add "$cidr" dev "$tun" || return 1; ra_capture ip -4 route add blackhole "$route" table "$table" || return 1; ra_capture ip -4 rule add priority "$pa" to "$rule_a" lookup "$table" || return 1; ra_capture ip -4 rule add priority "$pb" to "$rule_b" lookup "$table" || return 1; ra_capture nft add table inet "$nft" || return 1; ra_capture ip link add "$dns" type dummy || return 1; ra_capture ip link set dev "$dns" up || return 1; ra_capture resolvectl dns "$dns" "$server" || return 1; ra_capture resolvectl domain "$dns" "$domain" || return 1; ra_capture resolvectl default-route "$dns" no || return 1; ra_fixture_verify "$name" || return 1; ra_mut_mark_acquired "$name"; }
ra_fixture_verify() { local name="$1" spec tun cidr table route nft dns server pa pb rule_a rule_b; spec="$(jq -ce --arg n "$name" '.mutations[$n].identity' "$RA_CHECKPOINT")" || return 1; tun="$(jq -r '.tun' <<<"$spec")"; cidr="$(jq -r '.cidr' <<<"$spec")"; table="$(jq -r '.table' <<<"$spec")"; route="$(jq -r '.current_route' <<<"$spec")"; nft="$(jq -r '.nft_table' <<<"$spec")"; dns="$(jq -r '.dns_link' <<<"$spec")"; server="$(jq -r '.dns_server' <<<"$spec")"; pa="$(jq -r '.priority_a' <<<"$spec")"; pb="$(jq -r '.priority_b' <<<"$spec")"; rule_a="$(jq -r '.rule_a' <<<"$spec")"; rule_b="$(jq -r '.rule_b' <<<"$spec")"; ra_capture ip -j -d link show dev "$tun" || return 1; jq -e --arg n "$tun" 'length==1 and .[0].ifname==$n and .[0].linkinfo.info_kind=="tun"' <<<"$RA_CAPTURE" >/dev/null || return 1; ra_capture ip -4 address show dev "$tun" || return 1; grep -Fq "$cidr" <<<"$RA_CAPTURE" || return 1; ra_capture ip -j -4 route show table "$table" || return 1; jq -e --arg dst "$route" --arg t "$table" 'length==1 and .[0].type=="blackhole" and .[0].dst==$dst and (.[0].table|tostring)==$t' <<<"$RA_CAPTURE" >/dev/null || return 1; ra_capture ip -4 rule show priority "$pa" || return 1; grep -Eq "^${pa}: .*to ${rule_a//./\.} .*lookup $table" <<<"$RA_CAPTURE" || return 1; ra_capture ip -4 rule show priority "$pb" || return 1; grep -Eq "^${pb}: .*to ${rule_b//./\.} .*lookup $table" <<<"$RA_CAPTURE" || return 1; ra_capture nft -j list table inet "$nft" || return 1; jq -e --arg n "$nft" '[.nftables[]?|select(has("metainfo")|not)] as $x|($x|length)==1 and $x[0].table.family=="inet" and $x[0].table.name==$n' <<<"$RA_CAPTURE" >/dev/null || return 1; ra_capture ip -j -d link show dev "$dns" || return 1; jq -e --arg n "$dns" 'length==1 and .[0].ifname==$n and .[0].linkinfo.info_kind=="dummy"' <<<"$RA_CAPTURE" >/dev/null || return 1; ra_capture resolvectl status "$dns" --no-pager || return 1; grep -Fq "$server" <<<"$RA_CAPTURE"; }
ra_fixture_churn() { local name="$1" spec table current alternate; spec="$(jq -ce --arg n "$name" '.mutations[$n].identity' "$RA_CHECKPOINT")" || return 1; table="$(jq -r '.table' <<<"$spec")"; current="$(jq -r '.current_route' <<<"$spec")"; if [[ "$name" == fixture_b ]]; then alternate="203.0.113.64/32"; else alternate="198.51.100.252/32"; fi; ra_capture ip -4 route replace blackhole "$alternate" table "$table" || return 1; ra_capture ip -4 route del blackhole "$current" table "$table" || return 1; ra_state_jq '.mutations[$n].identity.current_route=$route' --arg n "$name" --arg route "$alternate"; }
ra_observe_link_exact() { local name="$1" kind="$2" count observed ifname; if ! ra_capture ip -j -d link show dev "$name"; then case "$RA_CAPTURE" in *"does not exist"*|*"Cannot find device"*|*"No such device"*) printf 'absent'; return 0 ;; *) return 1 ;; esac; fi; count="$(jq length <<<"$RA_CAPTURE" 2>/dev/null)" || return 1; [[ "$count" == 1 ]] || return 1; ifname="$(jq -r '.[0].ifname//""' <<<"$RA_CAPTURE")"; observed="$(jq -r '.[0].linkinfo.info_kind//""' <<<"$RA_CAPTURE")"; [[ "$ifname" == "$name" && "$observed" == "$kind" ]] || return 1; printf 'present'; }
ra_fixture_release_partial() { local name="$1" spec state tun dns table route pa pb rule_a rule_b nft tun_state dns_state n line route_state=absent rule_a_state=absent rule_b_state=absent nft_state=absent; spec="$(jq -ce --arg n "$name" '.mutations[$n].identity' "$RA_CHECKPOINT")" || return 1; state="$(jq -r --arg n "$name" '.mutations[$n].state' "$RA_CHECKPOINT")" || return 1; [[ "$state" == acquiring || "$state" == releasing ]] || return 1; tun="$(jq -r '.tun' <<<"$spec")"; dns="$(jq -r '.dns_link' <<<"$spec")"; table="$(jq -r '.table' <<<"$spec")"; route="$(jq -r '.current_route' <<<"$spec")"; pa="$(jq -r '.priority_a' <<<"$spec")"; pb="$(jq -r '.priority_b' <<<"$spec")"; rule_a="$(jq -r '.rule_a' <<<"$spec")"; rule_b="$(jq -r '.rule_b' <<<"$spec")"; nft="$(jq -r '.nft_table' <<<"$spec")"; tun_state="$(ra_observe_link_exact "$tun" tun)" || return 1; dns_state="$(ra_observe_link_exact "$dns" dummy)" || return 1; ra_capture ip -j -4 route show table "$table" || return 1; n="$(jq length <<<"$RA_CAPTURE")" || return 1; if [[ "$n" != 0 ]]; then [[ "$n" == 1 ]] || return 1; jq -e --arg dst "$route" --arg t "$table" '.[0].type=="blackhole" and .[0].dst==$dst and (.[0].table|tostring)==$t' <<<"$RA_CAPTURE" >/dev/null || return 1; route_state=present; fi; ra_capture ip -4 rule show priority "$pa" || return 1; if [[ -n "$RA_CAPTURE" ]]; then line="$RA_CAPTURE"; [[ "$(awk 'NF{n++} END{print n+0}' <<<"$line")" == 1 ]] && grep -Eq "^${pa}: .*to ${rule_a//./\.} .*lookup $table" <<<"$line" || return 1; rule_a_state=present; fi; ra_capture ip -4 rule show priority "$pb" || return 1; if [[ -n "$RA_CAPTURE" ]]; then line="$RA_CAPTURE"; [[ "$(awk 'NF{n++} END{print n+0}' <<<"$line")" == 1 ]] && grep -Eq "^${pb}: .*to ${rule_b//./\.} .*lookup $table" <<<"$line" || return 1; rule_b_state=present; fi; if ra_capture nft -j list table inet "$nft"; then jq -e --arg n "$nft" '[.nftables[]?|select(has("metainfo")|not)] as $x|($x|length)==1 and $x[0].table.family=="inet" and $x[0].table.name==$n' <<<"$RA_CAPTURE" >/dev/null || return 1; nft_state=present; else case "$RA_CAPTURE" in *"No such file or directory"*|*"does not exist"*) ;; *) return 1 ;; esac; fi; if [[ "$dns_state" == present ]]; then ra_capture resolvectl revert "$dns" || return 1; ra_capture ip link del dev "$dns" || return 1; fi; [[ "$nft_state" == absent ]] || ra_capture nft delete table inet "$nft" || return 1; [[ "$rule_b_state" == absent ]] || ra_capture ip -4 rule del priority "$pb" to "$rule_b" lookup "$table" || return 1; [[ "$rule_a_state" == absent ]] || ra_capture ip -4 rule del priority "$pa" to "$rule_a" lookup "$table" || return 1; [[ "$route_state" == absent ]] || ra_capture ip -4 route del blackhole "$route" table "$table" || return 1; [[ "$tun_state" == absent ]] || ra_capture ip link del dev "$tun" || return 1; ra_mut_mark_released "$name"; }
ra_fixture_release() { local name="$1" state; state="$(jq -r --arg n "$name" '.mutations[$n].state//"released"' "$RA_CHECKPOINT")" || return 1; [[ "$state" != released ]] || return 0; if [[ "$state" == acquired ]]; then ra_fixture_verify "$name" || return 1; ra_mut_begin_release "$name" || return 1; fi; ra_fixture_release_partial "$name"; }
ra_collision_require_disjoint() { local fixture="$1" spec address table pa pb hits=0 path tx; spec="$(jq -ce --arg n "$fixture" '.mutations[$n].identity' "$RA_CHECKPOINT")" || return 1; address="$(jq -r '.cidr|split("/")[0]' <<<"$spec")"; table="$(jq -r '.table' <<<"$spec")"; pa="$(jq -r '.priority_a' <<<"$spec")"; pb="$(jq -r '.priority_b' <<<"$spec")"; [[ -d "$RA_TRANSACTIONS" ]] || return 1; while IFS= read -r -d '' path; do tx="$(cat "$path")" || return 1; if jq -e '.owner=="podlaz" and .state=="committed"' <<<"$tx" >/dev/null 2>&1; then ((hits+=1)); if jq -e --arg a "$address" --arg t "$table" --argjson pa "$pa" --argjson pb "$pb" '..|scalars|select((tostring)==$a or (tostring)==$t or .==$pa or .==$pb)' <<<"$tx" >/dev/null 2>&1; then ra_die "product candidate allocation collides with occupied fixture resources"; return 1; fi; fi; done < <(find "$RA_TRANSACTIONS" -maxdepth 1 -type f -name '*.json' -print0 2>/dev/null); [[ "$hits" == 1 ]] || { ra_die "ownership expected exactly one committed candidate transaction"; return 1; }; ra_fixture_verify "$fixture"; }

ra_hook_allowed_name() { case "$1" in rollback-pause.arm|rollback-pause.ready|rollback-pause.continue|terminal-failure.trigger|terminal-data-plane-clean.ready|terminal-data-plane-clean.continue|privacy-teardown.ready|privacy-teardown.continue) return 0 ;; *) return 1 ;; esac; }
ra_systemd_hook_acquire() { local name="$1" path="$2" hook_dir="$3" content="$4" expected identity; [[ ! -e "$path" && ! -L "$path" && ! -e "$hook_dir" && ! -L "$hook_dir" ]] || { ra_die "ownership acceptance systemd hook path is occupied"; return 1; }; expected="$(printf '%s' "$content" | sha256sum | awk '{print $1}')" || return 1; identity="$(jq -cn --arg path "$path" --arg hook "$hook_dir" --arg sha "$expected" '{path:$path,hook_dir:$hook,sha256:$sha}')" || return 1; ra_mut_begin_acquire "$name" systemd_dropin "$identity" || return 1; mkdir -p "$(dirname "$path")" "$hook_dir" || return 1; chmod 0700 "$hook_dir" || return 1; printf '%s' "$content" >"$path" || return 1; chmod 0644 "$path" || return 1; [[ "$(ra_pkg_sha "$path")" == "$expected" ]] || return 1; ra_capture systemctl daemon-reload || return 1; ra_mut_mark_acquired "$name"; }
ra_systemd_hook_cleanup() { local name="$1" state path hook_dir expected child base; state="$(jq -r --arg n "$name" '.mutations[$n].state' "$RA_CHECKPOINT")" || return 1; path="$(jq -r --arg n "$name" '.mutations[$n].identity.path' "$RA_CHECKPOINT")"; hook_dir="$(jq -r --arg n "$name" '.mutations[$n].identity.hook_dir' "$RA_CHECKPOINT")"; expected="$(jq -r --arg n "$name" '.mutations[$n].identity.sha256' "$RA_CHECKPOINT")"; [[ "$state" != acquired ]] || ra_mut_begin_release "$name" || return 1; if [[ -e "$path" || -L "$path" ]]; then [[ -f "$path" && ! -L "$path" && "$(ra_pkg_sha "$path")" == "$expected" ]] || { ra_die "ownership acceptance systemd drop-in identity drifted"; return 1; }; rm -f "$path" || return 1; fi; if [[ -e "$hook_dir" || -L "$hook_dir" ]]; then [[ -d "$hook_dir" && ! -L "$hook_dir" ]] || return 1; while IFS= read -r -d '' child; do [[ -f "$child" && ! -L "$child" ]] || return 1; base="$(basename "$child")"; ra_hook_allowed_name "$base" || { ra_die "ownership foreign hook marker: $base"; return 1; }; rm -f "$child" || return 1; done < <(find "$hook_dir" -mindepth 1 -maxdepth 1 -print0); rmdir "$hook_dir" || return 1; fi; ra_capture systemctl daemon-reload || return 1; state="$(jq -r --arg n "$name" '.mutations[$n].state' "$RA_CHECKPOINT")"; if [[ "$state" == acquiring || "$state" == releasing ]]; then ra_mut_mark_released "$name"; fi; }

ra_is_remote_session() { [[ -n "${SSH_CONNECTION:-}${SSH_CLIENT:-}${SSH_TTY:-}" ]]; }
ra_nm_connection_active() { local connection="$1" device="$2"; ra_capture nmcli -t -f NAME,DEVICE connection show --active || return 1; awk -F: -v c="$connection" -v d="$device" '$1==c&&$2==d{found=1} END{exit !found}' <<<"$RA_CAPTURE"; }
ra_nm_link_identity() { local connection="$1" device="$2" addrs gateway; ra_nm_connection_active "$connection" "$device" || return 1; ra_capture ip -j -4 addr show dev "$device" || return 1; addrs="$(jq -c '[.[].addr_info[]?|select(.family=="inet")|(.local+"/"+(.prefixlen|tostring))]|sort' <<<"$RA_CAPTURE")" || return 1; [[ "$(jq length <<<"$addrs")" -gt 0 ]] || return 1; ra_capture ip -j -4 route show table main default dev "$device" || return 1; gateway="$(jq -r '[.[]?|.gateway//empty]|sort|.[0]//""' <<<"$RA_CAPTURE")" || return 1; [[ -n "$gateway" ]] || return 1; jq -cn --arg connection "$connection" --arg device "$device" --argjson addresses "$addrs" --arg gateway "$gateway" '{connection:$connection,device:$device,addresses:$addresses,gateway:$gateway}'; }
ra_dhcp_identity_changed() { local before="$1" after="$2"; if jq -e --argjson a "$after" '.addresses==$a.addresses and .gateway==$a.gateway' <<<"$before" >/dev/null; then printf 'false'; else printf 'true'; fi; }
ra_nm_reconcile() { local name="$1" state connection device; state="$(jq -r --arg n "$name" '.mutations[$n].state' "$RA_CHECKPOINT")"; connection="$(jq -r --arg n "$name" '.mutations[$n].identity.connection' "$RA_CHECKPOINT")"; device="$(jq -r --arg n "$name" '.mutations[$n].identity.device' "$RA_CHECKPOINT")"; if ra_nm_connection_active "$connection" "$device"; then if [[ "$state" == acquired ]]; then ra_mut_begin_release "$name" || return 1; fi; state="$(jq -r --arg n "$name" '.mutations[$n].state' "$RA_CHECKPOINT")"; if [[ "$state" == acquiring || "$state" == releasing ]]; then ra_mut_mark_released "$name"; fi; return 0; fi; if [[ "$state" == acquiring ]]; then ra_mut_mark_acquired "$name" || return 1; fi; state="$(jq -r --arg n "$name" '.mutations[$n].state' "$RA_CHECKPOINT")"; [[ "$state" != acquired ]] || ra_mut_begin_release "$name" || return 1; ra_capture nmcli connection up "$connection" || return 1; ra_nm_connection_active "$connection" "$device" || return 1; ra_mut_mark_released "$name"; }
ra_wifi_reconnect_once() { ((RA_ALLOW_WIFI==1)) || { ra_record wifi_reconnect SKIP_USER_REQUEST; return 0; }; if ra_is_remote_session; then ra_record wifi_reconnect SKIP_REMOTE_SESSION "remote session"; return 0; fi; command -v nmcli >/dev/null 2>&1 || { ra_record wifi_reconnect SKIP_HOST_CAPABILITY "nmcli unavailable"; return 0; }; ra_capture nmcli -t -f NAME,TYPE,DEVICE connection show --active || { ra_record wifi_reconnect SKIP_HOST_CAPABILITY "NetworkManager query failed"; return 0; }; local line connection device before after changed identity; line="$(awk -F: '$2=="802-11-wireless"&&$3!=""{print;exit}' <<<"$RA_CAPTURE")"; [[ -n "$line" ]] || { ra_record wifi_reconnect SKIP_HOST_CAPABILITY "no active Wi-Fi connection"; return 0; }; IFS=: read -r connection _ device <<<"$line"; before="$(ra_nm_link_identity "$connection" "$device")" || { ra_record wifi_reconnect SKIP_HOST_CAPABILITY "Wi-Fi uplink identity unavailable"; return 0; }; identity="$(jq -cn --arg connection "$connection" --arg device "$device" --argjson baseline "$before" '{connection:$connection,device:$device,baseline:$baseline,restoration_target:$baseline}')" || return 1; ra_mut_begin_acquire wifi_reconnect networkmanager_connection "$identity" || return 1; ra_capture nmcli connection down "$connection" || return 1; ra_mut_mark_acquired wifi_reconnect || return 1; ra_capture nmcli connection up "$connection" || return 1; after="$(ra_nm_link_identity "$connection" "$device")" || return 1; ra_mut_begin_release wifi_reconnect || return 1; ra_mut_mark_released wifi_reconnect || return 1; ra_wait_active 120 || return 1; ra_privacy_require_protected || return 1; ra_capture_user getent ahostsv4 example.com || return 1; ra_capture_user curl -4 -fsS --max-time 10 "$RA_PROBE_URL" -o /dev/null || return 1; changed="$(ra_dhcp_identity_changed "$before" "$after")" || return 1; ra_state_jq '.scenarios.wifi_reconnect.private={before:$before,after:$after,dhcp_identity_changed:$changed}' --argjson before "$before" --argjson after "$after" --argjson changed "$changed" || return 1; ra_record wifi_reconnect PASS "" "$(jq -cn --argjson changed "$changed" '{dhcp_identity_changed:$changed}')"; }

ra_proc_stat_fields() { local pid="$1" line rest; line="$(cat "/proc/$pid/stat" 2>/dev/null)" || return 1; [[ "$line" == *") "* ]] || return 1; rest="${line##*) }"; printf '%s' "$rest"; }
ra_proc_identity() { local pid="$1" expected_exe="$2" rest; local -a fields; [[ "$pid" =~ ^[0-9]+$ && "$pid" -gt 1 ]] || return 1; [[ "$(readlink -f "/proc/$pid/exe" 2>/dev/null)" == "$expected_exe" ]] || return 1; rest="$(ra_proc_stat_fields "$pid")" || return 1; read -r -a fields <<<"$rest"; ((${#fields[@]}>19)) || return 1; local cgroup; cgroup="$(awk -F: '$1==0&&$2==""{print $3}' "/proc/$pid/cgroup" 2>/dev/null)" || return 1; [[ "$cgroup" == /* ]] || return 1; jq -cn --argjson pid "$pid" --argjson parent "${fields[1]}" --argjson start "${fields[19]}" --arg exe "$expected_exe" --arg cgroup "$cgroup" '{pid:$pid,parent_pid:$parent,start_time_ticks:$start,exe:$exe,cgroup_path:$cgroup}'; }
ra_network_session_snapshot() { local boot; boot="$(ra_boot_id)" || return 1; [[ -f "$RA_CONTINUATION" && ! -L "$RA_CONTINUATION" ]] || return 1; jq -ce --arg boot "$boot" 'select(.schema_version=="podlaz.network-session-state.v1" and .owner=="podlaz" and .boot_id==$boot and (.session_id|type)=="string" and (.session_id|test("^[0-9a-f]{32}$")) and (.intent=="resume" or .intent=="terminal"))' "$RA_CONTINUATION"; }
ra_active_resource_identity() {
  local daemon daemon_identity cgroup_rel status active_tx path tx_count=0 tx_json="" tx_path="" tx_id xray_pid config_ref child_count xray_identity session cmdline_refs
  daemon="$(ra_main_pid)" || { ra_die "ownership resource daemon MainPID unavailable"; return 1; }
  daemon_identity="$(ra_proc_identity "$daemon" /usr/bin/podlazd)" || { ra_die "ownership daemon process identity ambiguous"; return 1; }
  cgroup_rel="$(jq -r '.cgroup_path' <<<"$daemon_identity")"; [[ "$cgroup_rel" == */podlazd.service ]] || { ra_die "ownership daemon outside podlazd service cgroup"; return 1; }
  status="$(ra_status_json)" || return 1; active_tx="$(jq -r '.active_transaction_id//""' <<<"$status")" || return 1
  [[ -d "$RA_TRANSACTIONS" ]] || { ra_die "ownership transaction inventory unavailable"; return 1; }
  while IFS= read -r -d '' path; do
    if jq -e '.owner=="podlaz" and .mode=="tun" and .state=="committed" and (.requires_cleanup//false)==false' "$path" >/dev/null 2>&1; then
      ((tx_count+=1)); tx_json="$(cat "$path")" || return 1; tx_path="$path"
    fi
  done < <(find "$RA_TRANSACTIONS" -maxdepth 1 -type f -name '*.json' -print0 2>/dev/null)
  [[ "$tx_count" == 1 ]] || { ra_die "ownership active TUN transaction attribution ambiguous"; return 1; }
  tx_id="$(jq -r '.id//""' <<<"$tx_json")" || return 1; [[ -n "$tx_id" ]] || return 1
  [[ -z "$active_tx" || "$active_tx" == "$tx_id" ]] || { ra_die "ownership status active transaction does not match durable transaction"; return 1; }
  child_count="$(jq '[.rollback.child_processes[]?|select(.owner=="podlaz" and .label=="xray" and (.pid|type)=="number" and (.config_ref|type)=="string")]|length' <<<"$tx_json")" || return 1
  [[ "$child_count" == 1 ]] || { ra_die "ownership supervised Xray child attribution ambiguous"; return 1; }
  xray_pid="$(jq -r '.rollback.child_processes[]|select(.owner=="podlaz" and .label=="xray")|.pid' <<<"$tx_json")" || return 1
  config_ref="$(jq -r '.rollback.child_processes[]|select(.owner=="podlaz" and .label=="xray")|.config_ref' <<<"$tx_json")" || return 1
  [[ "$config_ref" == /* ]] || { ra_die "ownership supervised Xray config_ref is not absolute"; return 1; }
  xray_identity="$(ra_proc_identity "$xray_pid" /usr/lib/podlaz/xray)" || { ra_die "ownership supervised Xray process identity ambiguous"; return 1; }
  jq -e --argjson d "$daemon" --arg cg "$cgroup_rel" '.parent_pid==$d and .cgroup_path==$cg' <<<"$xray_identity" >/dev/null || { ra_die "ownership supervised Xray is outside exact daemon parent/cgroup"; return 1; }
  cmdline_refs="$(tr '\0' '\n' <"/proc/$xray_pid/cmdline" 2>/dev/null | awk -v ref="$config_ref" 'prev {if($0==ref)n++; prev=0} $0=="-config"||$0=="-c"{prev=1} END{print n+0}')" || return 1
  [[ "$cmdline_refs" == 1 ]] || { ra_die "ownership supervised Xray command does not reference exact config_ref"; return 1; }
  session="$(ra_network_session_snapshot)" || { ra_die "ownership Network Session identity unavailable"; return 1; }
  jq -cn --arg transaction_id "$tx_id" --arg transaction_file "$tx_path" --arg session_id "$(jq -r '.session_id' <<<"$session")" --arg config_ref "$config_ref" --argjson daemon "$daemon_identity" --argjson xray "$xray_identity" '{transaction_id:$transaction_id,transaction_file:$transaction_file,session_id:$session_id,config_ref:$config_ref,daemon:$daemon,xray:$xray}'
}

ra_fd_socket_maps() {
  local pid="$1" out="$2" f
  : >"$out"
  for f in tcp tcp6; do [[ -r "/proc/$pid/net/$f" ]] || continue; awk 'NR>1 && NF>=10 {print $10" tcp "$4}' "/proc/$pid/net/$f" >>"$out"; done
  for f in udp udp6; do [[ -r "/proc/$pid/net/$f" ]] || continue; awk 'NR>1 && NF>=10 {print $10" udp "$4}' "/proc/$pid/net/$f" >>"$out"; done
  [[ ! -r "/proc/$pid/net/unix" ]] || awk 'NR>1 && NF>=7 {print $7" unix -"}' "/proc/$pid/net/unix" >>"$out"
  sort -u -o "$out" "$out"
}
ra_proc_sample() {
  local pid="$1" role="$2" identity rest; local -a fields; identity="$(ra_proc_identity "$pid" "$( [[ "$role" == daemon ]] && printf /usr/bin/podlazd || printf /usr/lib/podlaz/xray )")" || return 1; rest="$(ra_proc_stat_fields "$pid")" || return 1; read -r -a fields <<<"$rest"; local rss=0 pss=0 threads=0 tasks=0 fds=0 socket_fds=0 tcp=0 tcp_listen=0 tcp_est=0 tcp_other=0 udp=0 udp_conn=0 udp_unconn=0 udp_other=0 unix=0 unclassified=0 pipes=0 anon=0 regular=0 other=0 cpu=0 fd target inode map rec proto state
  rss="$(awk '/^VmRSS:/{print $2;exit}' "/proc/$pid/status" 2>/dev/null || printf 0)"; pss="$(awk '/^Pss:/{print $2;exit}' "/proc/$pid/smaps_rollup" 2>/dev/null || printf 0)"; threads="$(awk '/^Threads:/{print $2;exit}' "/proc/$pid/status" 2>/dev/null || printf 0)"; tasks="$(find "/proc/$pid/task" -mindepth 1 -maxdepth 1 2>/dev/null | wc -l)"; cpu=$((fields[11]+fields[12])); map="$(mktemp)" || return 1; ra_fd_socket_maps "$pid" "$map" || { rm -f "$map"; return 1; }
  while IFS= read -r fd; do [[ -n "$fd" ]] || continue; ((fds+=1)); target="$(readlink "$fd" 2>/dev/null || true)"; case "$target" in socket:\[*\]) ((socket_fds+=1)); inode="${target#socket:[}"; inode="${inode%]}"; rec="$(awk -v i="$inode" '$1==i{print $2" "$3;exit}' "$map")"; if [[ -z "$rec" ]]; then ((unclassified+=1)); else read -r proto state <<<"$rec"; case "$proto" in tcp) ((tcp+=1)); case "$state" in 0A) ((tcp_listen+=1));; 01) ((tcp_est+=1));; *) ((tcp_other+=1));; esac ;; udp) ((udp+=1)); case "$state" in 01) ((udp_conn+=1));; 07) ((udp_unconn+=1));; *) ((udp_other+=1));; esac ;; unix) ((unix+=1));; *) ((unclassified+=1));; esac; fi ;; pipe:\[*\]) ((pipes+=1));; anon_inode:*) ((anon+=1));; /*) ((regular+=1));; *) ((other+=1));; esac; done < <(find "/proc/$pid/fd" -mindepth 1 -maxdepth 1 -print 2>/dev/null); rm -f "$map"
  jq -cn --arg role "$role" --argjson pid "$pid" --argjson rss_kb "${rss:-0}" --argjson pss_kb "${pss:-0}" --argjson threads "${threads:-0}" --argjson tasks "$tasks" --argjson fds "$fds" --argjson socket_fds "$socket_fds" --argjson tcp_socket_fds "$tcp" --argjson tcp_listen_socket_fds "$tcp_listen" --argjson tcp_established_socket_fds "$tcp_est" --argjson tcp_other_socket_fds "$tcp_other" --argjson udp_socket_fds "$udp" --argjson udp_connected_socket_fds "$udp_conn" --argjson udp_unconnected_socket_fds "$udp_unconn" --argjson udp_other_socket_fds "$udp_other" --argjson unix_socket_fds "$unix" --argjson unclassified_socket_fds "$unclassified" --argjson pipe_fds "$pipes" --argjson anon_inode_fds "$anon" --argjson regular_fds "$regular" --argjson other_fds "$other" --argjson cpu_ticks "$cpu" '{role:$role,pid:$pid,rss_kb:$rss_kb,pss_kb:$pss_kb,threads:$threads,tasks:$tasks,fds:$fds,socket_fds:$socket_fds,tcp_socket_fds:$tcp_socket_fds,tcp_listen_socket_fds:$tcp_listen_socket_fds,tcp_established_socket_fds:$tcp_established_socket_fds,tcp_other_socket_fds:$tcp_other_socket_fds,udp_socket_fds:$udp_socket_fds,udp_connected_socket_fds:$udp_connected_socket_fds,udp_unconnected_socket_fds:$udp_unconn,udp_other_socket_fds:$udp_other,unix_socket_fds:$unix,unclassified_socket_fds:$unclassified,pipe_fds:$pipes,anon_inode_fds:$anon,regular_fds:$regular,other_fds:$other,cpu_ticks:$cpu}'
}
ra_resource_sample() { local tag="$1" identity daemon xray cgroup_rel cgroup mem=0 peak=0 pids=0 cpu=0 d x; identity="$(ra_active_resource_identity)" || return 1; daemon="$(jq -r '.daemon.pid' <<<"$identity")"; xray="$(jq -r '.xray.pid' <<<"$identity")"; cgroup_rel="$(jq -r '.daemon.cgroup_path' <<<"$identity")"; cgroup="/sys/fs/cgroup${cgroup_rel}"; [[ -r "$cgroup/memory.current" ]] && mem="$(cat "$cgroup/memory.current")"; [[ -r "$cgroup/memory.peak" ]] && peak="$(cat "$cgroup/memory.peak")"; [[ -r "$cgroup/pids.current" ]] && pids="$(cat "$cgroup/pids.current")"; [[ -r "$cgroup/cpu.stat" ]] && cpu="$(awk '$1=="usage_usec"{print $2}' "$cgroup/cpu.stat")"; d="$(ra_proc_sample "$daemon" daemon)" || return 1; x="$(ra_proc_sample "$xray" xray)" || return 1; jq -cn --arg tag "$tag" --argjson elapsed "$(date +%s)" --argjson identity "$identity" --argjson daemon "$d" --argjson xray "$x" --argjson memory_current "$mem" --argjson memory_peak "$peak" --argjson pids_current "$pids" --argjson cpu_usage_usec "${cpu:-0}" '{tag:$tag,elapsed:$elapsed,identity:$identity,daemon:$daemon,xray:$xray,service:{memory_current:$memory_current,memory_peak:$memory_peak,pids_current:$pids_current,cpu_usage_usec:$cpu_usage_usec}}'; }
ra_inactive_sample() { local tag="$1" daemon identity cgroup_rel cgroup mem=0 peak=0 pids=0 fds=0 cpu=0; daemon="$(ra_main_pid)" || return 1; identity="$(ra_proc_identity "$daemon" /usr/bin/podlazd)" || return 1; cgroup_rel="$(jq -r '.cgroup_path' <<<"$identity")"; cgroup="/sys/fs/cgroup${cgroup_rel}"; [[ -r "$cgroup/memory.current" ]] && mem="$(cat "$cgroup/memory.current")"; [[ -r "$cgroup/memory.peak" ]] && peak="$(cat "$cgroup/memory.peak")"; [[ -r "$cgroup/pids.current" ]] && pids="$(cat "$cgroup/pids.current")"; [[ -r "$cgroup/cpu.stat" ]] && cpu="$(awk '$1=="usage_usec"{print $2}' "$cgroup/cpu.stat")"; fds="$(find "/proc/$daemon/fd" -mindepth 1 -maxdepth 1 2>/dev/null | wc -l)"; jq -cn --arg tag "$tag" --argjson identity "$identity" --argjson memory_current "$mem" --argjson memory_peak "$peak" --argjson pids_current "$pids" --argjson daemon_fds "$fds" --argjson cpu_usage_usec "${cpu:-0}" '{tag:$tag,identity:$identity,memory_current:$memory_current,memory_peak:$memory_peak,pids_current:$pids_current,daemon_fds:$daemon_fds,cpu_usage_usec:$cpu_usage_usec}'; }

ra_resource_summary_file() {
  local file="$1"
  [[ -s "$file" ]] || return 1
  jq -s -e '
    def vals($p): [.[] | getpath($p) | numbers];
    def stats($p): (vals($p)) as $v | ($v|sort) as $s | ($v|length) as $n |
      if $n==0 then null else {min:$s[0],median:(if ($n%2)==1 then $s[($n/2|floor)] else (($s[$n/2-1]+$s[$n/2])/2) end),max:$s[-1],sampled_peak:$s[-1],last:$v[-1],delta:($v[-1]-$v[0])} end;
    (length) as $n | select($n>0) |
    ([.[].identity.transaction_id]|unique) as $tx | ([.[].identity.session_id]|unique) as $sessions |
    select(($tx|length)==1 and ($sessions|length)==1) |
    {sample_count:$n,
     identity:{transaction_id:$tx[0],session_id:$sessions[0],config_ref:.[0].identity.config_ref,daemon:.[0].identity.daemon,xray:.[0].identity.xray,
       daemon_generation_count:([.[]|[.identity.daemon.pid,.identity.daemon.start_time_ticks]]|unique|length),
       xray_generation_count:([.[]|[.identity.xray.pid,.identity.xray.start_time_ticks]]|unique|length)},
     measured_seconds:((.[-1].elapsed//0)-(.[0].elapsed//0)),
     daemon:{rss_kb:stats(["daemon","rss_kb"]),pss_kb:stats(["daemon","pss_kb"]),threads:stats(["daemon","threads"]),tasks:stats(["daemon","tasks"]),fds:stats(["daemon","fds"]),socket_fds:stats(["daemon","socket_fds"]),cpu_ticks:stats(["daemon","cpu_ticks"])},
     xray:{rss_kb:stats(["xray","rss_kb"]),pss_kb:stats(["xray","pss_kb"]),threads:stats(["xray","threads"]),tasks:stats(["xray","tasks"]),fds:stats(["xray","fds"]),socket_fds:stats(["xray","socket_fds"]),cpu_ticks:stats(["xray","cpu_ticks"])},
     service:{memory_current:stats(["service","memory_current"]),pids_current:stats(["service","pids_current"]),cpu_usage_usec:stats(["service","cpu_usage_usec"]),lifetime_memory_peak:([.[].service.memory_peak|numbers]|max)}}' "$file"
}
ra_resource_compare_sessions() {
  local first="$1" second="$2" baseline="${3:-null}"
  jq -cn --argjson first "$first" --argjson second "$second" --argjson baseline "$baseline" '
    def d($a;$b): (($b.last//0)-($a.last//0));
    ($first.identity.session_id != $second.identity.session_id) as $different_session |
    (([$first.identity.xray.pid,$first.identity.xray.start_time_ticks] != [$second.identity.xray.pid,$second.identity.xray.start_time_ticks])) as $xray_replaced |
    (($first.identity.daemon.cgroup_path==$second.identity.daemon.cgroup_path) and ($first.identity.xray.cgroup_path==$second.identity.xray.cgroup_path)) as $same_cgroup |
    {compared:true,first_session_id:$first.identity.session_id,second_session_id:$second.identity.session_id,same_session:($different_session|not),
     structural_nonaccumulation:($different_session and $xray_replaced and $same_cgroup),
     deltas:{daemon_rss_last_kb:d($first.daemon.rss_kb;$second.daemon.rss_kb),daemon_fds_last:d($first.daemon.fds;$second.daemon.fds),xray_rss_last_kb:d($first.xray.rss_kb;$second.xray.rss_kb),xray_fds_last:d($first.xray.fds;$second.xray.fds),service_memory_current_last:d($first.service.memory_current;$second.service.memory_current),service_pids_last:d($first.service.pids_current;$second.service.pids_current)},
     warmed_inactive_baseline:$baseline}'
}

ra_suspend_once() {
  ((RA_ALLOW_SUSPEND==1)) || { ra_record suspend_resume SKIP_USER_REQUEST; return 0; }
  if ra_is_remote_session; then ra_record suspend_resume SKIP_REMOTE_SESSION "remote session"; return 0; fi
  command -v rtcwake >/dev/null 2>&1 || { ra_record suspend_resume SKIP_HOST_CAPABILITY "rtcwake unavailable"; return 0; }
  local before after observed before_sample immediate settle before_identity after_identity generations
  before="$(date +%s)" || return 1; before_sample="$(ra_resource_sample suspend_pre)" || return 1; before_identity="$(jq -c '.identity' <<<"$before_sample")" || return 1
  ra_state_jq '.scenarios.suspend_resume.private=((.scenarios.suspend_resume.private//{})+{prepared_at_epoch:$epoch,pre_identity:$identity})' --argjson epoch "$before" --argjson identity "$before_identity" || return 1
  sync -f "$RA_CHECKPOINT" 2>/dev/null || true; sync -f "$RA_PRIVATE_DIR" 2>/dev/null || true
  if ! ra_capture rtcwake -m mem -s 75; then ra_record suspend_resume SKIP_HOST_CAPABILITY "bounded rtcwake suspend unavailable"; return 0; fi
  after="$(date +%s)" || return 1; observed=$((after-before))
  if ((observed<60 || observed>180)); then ra_record suspend_resume SKIP_HOST_CAPABILITY "host did not demonstrate a meaningful bounded suspend" "$(jq -cn --argjson observed "$observed" '{observed_suspend_seconds:$observed}')"; return 0; fi
  ra_wait_active 180 || return 1; ra_privacy_require_protected || return 1; ra_capture_user getent ahostsv4 example.com || return 1; ra_capture_user curl -4 -fsS --max-time 10 "$RA_PROBE_URL" -o /dev/null || return 1
  immediate="$(ra_resource_sample suspend_immediate)" || return 1; if [[ -n "$RA_SOAK_SAMPLES_FILE" ]]; then printf '%s\n' "$immediate" >>"$RA_SOAK_SAMPLES_FILE"; fi
  if [[ "${RELEASE_ACCEPTANCE_TEST_MODE:-0}" != 1 ]]; then sleep 10; fi
  settle="$(ra_resource_sample suspend_settled)" || return 1; if [[ -n "$RA_SOAK_SAMPLES_FILE" ]]; then printf '%s\n' "$settle" >>"$RA_SOAK_SAMPLES_FILE"; fi
  after_identity="$(jq -c '.identity' <<<"$settle")"; generations="$(jq -cn --argjson before "$before_identity" --argjson after "$after_identity" '{daemon_changed:([$before.daemon.pid,$before.daemon.start_time_ticks]!=[$after.daemon.pid,$after.daemon.start_time_ticks]),xray_changed:([$before.xray.pid,$before.xray.start_time_ticks]!=[$after.xray.pid,$after.xray.start_time_ticks])}')"
  ra_state_jq '.scenarios.suspend_resume.private+=({observed_suspend_seconds:$observed,post_identity:$identity,generation_changes:$generations})' --argjson observed "$observed" --argjson identity "$after_identity" --argjson generations "$generations" || return 1
  ra_record suspend_resume PASS "" "$(jq -cn --argjson observed "$observed" --argjson generations "$generations" '{observed_suspend_seconds:$observed,generation_changes:$generations}')"
}

ra_soak_run() {
  local seconds interval doctor_interval start now next next_doctor elapsed wifi_done=0 suspend_done=0 fixture_done=0 sample summary measured
  if [[ "${RELEASE_ACCEPTANCE_TEST_MODE:-0}" == 1 ]]; then seconds="${RELEASE_ACCEPTANCE_TEST_SOAK_SECONDS:-3}"; interval=1; doctor_interval=2; else seconds=$((RA_SOAK_MINUTES*60)); interval=60; doctor_interval=600; fi
  start="$(date +%s)"; next="$start"; next_doctor="$start"; RA_SOAK_SAMPLES_FILE="$RA_PRIVATE_DIR/soak-samples.jsonl"; printf '' | ra_artifact_file_write "$RA_SOAK_SAMPLES_FILE" || return 1
  while :; do now="$(date +%s)"; elapsed=$((now-start)); ((elapsed<seconds)) || break; if ((now>=next)); then ra_wait_active 30 || return 1; ra_privacy_require_protected || return 1; ra_capture_user getent ahostsv4 example.com || return 1; ra_capture_user curl -4 -fsS --max-time 10 "$RA_PROBE_URL" -o /dev/null || return 1; sample="$(ra_resource_sample soak)" || return 1; printf '%s\n' "$sample" | ra_artifact_file_append "$RA_SOAK_SAMPLES_FILE" || return 1; next=$((now+interval)); fi; if ((now>=next_doctor)); then ra_product doctor --tun --json >/dev/null || return 1; next_doctor=$((now+doctor_interval)); fi; if ((fixture_done==0 && elapsed>=seconds/3)); then ra_fixture_acquire fixture_b || return 1; ra_fixture_churn fixture_b || return 1; ra_wait_active 60 || return 1; ra_privacy_require_protected || return 1; ra_fixture_verify fixture_b || return 1; ra_record active_coexistence PASS; fixture_done=1; fi; if ((wifi_done==0 && elapsed>=seconds/2)); then ra_wifi_reconnect_once || return 1; wifi_done=1; fi; if ((suspend_done==0 && elapsed>=(seconds*2)/3)); then ra_suspend_once || return 1; suspend_done=1; fi; sleep 1; done
  ((fixture_done==1)) || { ra_fixture_acquire fixture_b || return 1; ra_fixture_churn fixture_b || return 1; ra_wait_active || return 1; ra_fixture_verify fixture_b || return 1; ra_record active_coexistence PASS; }
  ((wifi_done==1)) || ra_wifi_reconnect_once || return 1; ((suspend_done==1)) || ra_suspend_once || return 1; ra_fixture_release fixture_b || return 1
  now="$(date +%s)"; measured=$((now-start)); summary="$(ra_resource_summary_file "$RA_SOAK_SAMPLES_FILE")" || return 1
  ra_state_jq '.private.resource.first_session_summary=$summary|.private.resource.actual_soak_seconds=$measured' --argjson summary "$summary" --argjson measured "$measured" || return 1
  ra_record resource_soak PASS "" "$(jq -cn --argjson measured "$measured" --argjson samples "$(wc -l <"$RA_SOAK_SAMPLES_FILE")" '{measured_seconds:$measured,samples:$samples}')"; RA_SOAK_SAMPLES_FILE=""
}
ra_second_session_observe() { local seconds start now sample summary first baseline comparison file; if [[ "${RELEASE_ACCEPTANCE_TEST_MODE:-0}" == 1 ]]; then seconds=2; else seconds=300; fi; start="$(date +%s)"; file="$RA_PRIVATE_DIR/second-session.jsonl"; printf '' | ra_artifact_file_write "$file" || return 1; while :; do now="$(date +%s)"; ((now-start<seconds)) || break; ra_wait_active 30 || return 1; ra_privacy_require_protected || return 1; sample="$(ra_resource_sample second_session)" || return 1; printf '%s\n' "$sample" | ra_artifact_file_append "$file" || return 1; if [[ "${RELEASE_ACCEPTANCE_TEST_MODE:-0}" == 1 ]]; then sleep 1; else sleep 30; fi; done; summary="$(ra_resource_summary_file "$file")" || return 1; first="$(jq -ce '.private.resource.first_session_summary' "$RA_CHECKPOINT")" || return 1; baseline="$(jq -c '.private.warmed_inactive//null' "$RA_CHECKPOINT")" || return 1; comparison="$(ra_resource_compare_sessions "$first" "$summary" "$baseline")" || return 1; ra_state_jq '.private.resource.second_session_summary=$summary|.private.resource.session_comparison=$comparison' --argjson summary "$summary" --argjson comparison "$comparison" || return 1; if [[ "$(jq -r '.structural_nonaccumulation' <<<"$comparison")" == true ]]; then ra_record reconnect_resource_nonaccumulation PASS "" "$(jq -c '{compared,structural_nonaccumulation,deltas}' <<<"$comparison")"; else ra_record reconnect_resource_nonaccumulation FAIL "structural resource ownership accumulated" "$(jq -c '{compared,structural_nonaccumulation,deltas}' <<<"$comparison")"; return 1; fi; }
